deployment:
  tasks:
    - export DEPLOYPATH=/home/praj1261/public_html/

    - find $DEPLOYPATH -maxdepth 1 -type f ! -name 'biaya.html' -exec rm -f {} \;

    - /bin/cp -r ./website-and-photos/* $DEPLOYPATH
